spring.application.name=OrderService
app.jms.order-created-queue=order.created

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ordersdb
spring.datasource.username=ordersuser
spring.datasource.password=orderspw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect